<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.alipay.sofa</groupId>
        <artifactId>sofaboot-dependencies</artifactId>
        <version>3.16.3</version>
    </parent>
    <groupId>com.anyex.apps</groupId>
    <artifactId>apps-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>ExchangeBiz</name>
    <description>Exchange-Server with IMBiz-Server project</description>

    <modules>
        <module>apps-service</module>
        <module>apps-commons</module>
        <module>apps-fronts</module>
        <module>apps-backend</module>
    </modules>

    <properties>
        <java.version>1.8</java.version>
        <oltu.version>1.0.2</oltu.version>
        <zookeeper-version>3.5.5</zookeeper-version>
        <build.path>${user.home}/Downloads/apps4exchange/</build.path>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <spring.version>5.3.22</spring.version>
        <jackson.version>2.9.10</jackson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- mybatis-plus -->
            <!--            <dependency>-->
            <!--                <groupId>com.baomidou</groupId>-->
            <!--                <artifactId>mybatis-plus-boot-starter</artifactId>-->
            <!--                <version>3.5.3</version>-->
            <!--            </dependency>-->
            <!--海康威视-->
            <dependency>
                <groupId>com.hikvision.ga</groupId>
                <artifactId>artemis-http-client</artifactId>
                <version>1.1.3</version>
                <exclusions>
                    <exclusion>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-classic</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!--            <dependency>-->
            <!--                <groupId>io.minio</groupId>-->
            <!--                <artifactId>minio</artifactId>-->
            <!--                <version>8.1.0</version>-->
            <!--            </dependency>-->
            <!--华为OBS-->
            <dependency>
                <groupId>com.huaweicloud</groupId>
                <artifactId>esdk-obs-java</artifactId>
                <version>3.22.3.1</version>
            </dependency>
            <!--阿里图片识别-->
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>ocr20191230</artifactId>
                <version>1.0.26</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>3.14.5</version>
            </dependency>
            <!-- mybatisPlusPlus -->
            <!--            <dependency>-->
            <!--                <groupId>com.github.jeffreyning</groupId>-->
            <!--                <artifactId>mybatisplus-plus</artifactId>-->
            <!--                <version>1.5.1-RELEASE</version>-->
            <!--            </dependency>-->
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot</artifactId>
                <version>2.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot</artifactId>
                <version>1.4.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--极光相关依赖-->
            <dependency>
                <groupId>cn.jpush.api</groupId>
                <artifactId>jpush-client</artifactId>
                <version>3.3.10</version>
            </dependency>
            <dependency>
                <groupId>com.esotericsoftware</groupId>
                <artifactId>kryo-shaded</artifactId>
                <version>4.0.2</version>
            </dependency>
            <dependency>
                <groupId>commons-validator</groupId>
                <artifactId>commons-validator</artifactId>
                <version>1.4.1</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.6</version>
            </dependency>
            <dependency>
                <groupId>oro</groupId>
                <artifactId>oro</artifactId>
                <version>2.0.8</version>
            </dependency>
            <dependency>
                <groupId>com.lmax</groupId>
                <artifactId>disruptor</artifactId>
                <version>3.4.2</version>
            </dependency>
            <dependency>
                <groupId>org.jsoup</groupId>
                <artifactId>jsoup</artifactId>
                <version>1.12.1</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>2.7.2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-keyvalue</artifactId>
                <version>2.7.2</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-resolver-dns</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-dns</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-haproxy</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http2</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-memcache</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-resolver</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler-proxy</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-mqtt</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-redis</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-smtp</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-socks</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-stomp</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-xml</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-unix-common</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-rxtx</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-sctp</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-udt</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-epoll</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-kqueue</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-buffer</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-common</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-transport-native-epoll</artifactId>
                <version>4.1.79.Final</version>
            </dependency>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-core</artifactId>
                <version>3.3.22.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-framework</artifactId>
                <version>4.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-recipes</artifactId>
                <version>4.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-redis</artifactId>
                <version>2.7.3</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-redis</artifactId>
                <version>2.7.2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-mongodb</artifactId>
                <version>2.7.3</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-mongodb</artifactId>
                <version>3.4.2</version>
            </dependency>
            <!-- bouncycastle -->
            <!--            <dependency>-->
            <!--                <groupId>org.bouncycastle</groupId>-->
            <!--                <artifactId>bcprov-jdk15on</artifactId>-->
            <!--                <version>1.64</version>-->
            <!--            </dependency>-->
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk16</artifactId>
                <version>1.45</version>
            </dependency>
            <!-- base64 -->
            <dependency>
                <groupId>net.iharder</groupId>
                <artifactId>base64</artifactId>
                <version>2.3.9</version>
            </dependency>
            <!-- aws sdk -->
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.213</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- aliyun sdk -->
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-afs</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-sts</artifactId>
                <version>3.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-core</artifactId>
                <version>4.4.2</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>2.7.0</version>
            </dependency>
            <!-- aliyun 验证码2.0 sdk -->
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>captcha20230305</artifactId>
                <version>1.1.2</version>
            </dependency>
            <!--            <dependency>-->
            <!--                <groupId>org.apache.poi</groupId>-->
            <!--                <artifactId>poi-ooxml</artifactId>-->
            <!--                <version>3.13</version>-->
            <!--            </dependency>-->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>4.1.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>4.1.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml-schemas</artifactId>
                <version>4.1.2</version>
            </dependency>

            <dependency>
                <groupId>cz.mallat.uasparser</groupId>
                <artifactId>uasparser</artifactId>
                <version>0.6.2</version>
            </dependency>
            <dependency>
                <groupId>com.maxmind.geoip</groupId>
                <artifactId>geoip-api</artifactId>
                <version>1.3.1</version>
            </dependency>
            <!-- kaptcha -->
            <dependency>
                <groupId>com.chaoxing</groupId>
                <artifactId>kaptcha</artifactId>
                <version>2.3.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.shiro</groupId>
                <artifactId>shiro-core</artifactId>
                <version>1.4.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.shiro</groupId>
                <artifactId>shiro-web</artifactId>
                <version>1.4.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.shiro</groupId>
                <artifactId>shiro-spring</artifactId>
                <version>1.4.1</version>
            </dependency>
            <!--<dependency>
                <groupId>com.auth0</groupId>
                <artifactId>java-jwt</artifactId>
                <version>3.8.3</version>
            </dependency>-->
            <dependency>
                <groupId>javax.mail</groupId>
                <artifactId>mail</artifactId>
                <version>1.4.7</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>25.1-jre</version>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>1.4.1</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.github.xiaoymin/knife4j-spring-boot-starter -->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-spring-boot-starter</artifactId>
                <version>2.0.4</version>
            </dependency>

            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-core</artifactId>
                <version>1.28.0</version>
            </dependency>
            <!--activiti工作流引入-->
            <!--            <dependency>-->
            <!--                <groupId>org.activiti</groupId>-->
            <!--                <artifactId>activiti-spring-boot-starter</artifactId>-->
            <!--                <version>7.0.0.Beta2</version>-->
            <!--            </dependency>-->
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-core</artifactId>
                <version>5.7.3</version>
            </dependency>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-core</artifactId>
                <version>3.5.0</version>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-core</artifactId>
                <version>1.9.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.baidu.aip</groupId>
                <artifactId>java-sdk</artifactId>
                <version>4.15.1</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-simple</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!--            <dependency>-->
            <!--                <groupId>com.alibaba</groupId>-->
            <!--                <artifactId>easyexcel</artifactId>-->
            <!--                <version>3.3.1</version>-->
            <!--            </dependency>-->
            <!--easypoi导入导出-->
            <dependency>
                <groupId>cn.afterturn</groupId>
                <artifactId>easypoi-base</artifactId>
                <version>4.2.0</version>
            </dependency>

            <dependency>
                <groupId>com.google.firebase</groupId>
                <artifactId>firebase-admin</artifactId>
                <version>9.1.1</version>
            </dependency>

            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>2.0.21</version>
            </dependency>
            <dependency>
                <groupId>org.mapdb</groupId>
                <artifactId>mapdb</artifactId>
                <version>3.1.0</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>retrofit</artifactId>
                <version>2.3.0</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-jackson</artifactId>
                <version>2.3.0</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-scalars</artifactId>
                <version>2.3.0</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>adapter-rxjava</artifactId>
                <version>2.3.0</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.retrofit2</groupId>
                <artifactId>converter-gson</artifactId>
                <version>2.3.0</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>exchangebiz-dev</id>
            <properties>
                <env>exchangebiz-dev</env>
                <withdraw.interface.switch>FALSE</withdraw.interface.switch>
                <port.admin>9280</port.admin>
                <port.app>9281</port.app>
                <port.web>9282</port.web>
                <port.api>9283</port.api>
                <port.socket>9284</port.socket>
                <port.rpcServer>12310</port.rpcServer>
                <jpush.appkey>e6b7fda65d7cf7e8b3a</jpush.appkey>
                <jpush.secret>aa46dd030b3d7e891</jpush.secret>
                <weibo.appkey>11111</weibo.appkey>
                <weibo.secret>11111</weibo.secret>
                <weibo.redirect>http://baidu.com</weibo.redirect>
                <qq.appkey>11111</qq.appkey>
                <qq.secret>11111</qq.secret>
                <qq.redirect>http://baidu.com</qq.redirect>
                <!-- 微信小程序 -->
                <weixin.appkey>wxfc4526888e890cdd</weixin.appkey>
                <weixin.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.secret>
                <weixin.open.appkey>wxfc4526888e890cdd</weixin.open.appkey>
                <weixin.open.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.open.secret>
                <weixin.redirect>http://webfhsc.vipgz4.91tunnel.com/api</weixin.redirect>
                <!-- 微信小程序 -->
                <aliyun.afs.appkey>FFFF00000000</aliyun.afs.appkey>
                <aliyun.access.key>LTAI5tBAKUNBfCswtMQgGPZT</aliyun.access.key>
                <aliyun.access.secret>AEcdi4R8hZUHZxxnDSsMia4xclJOFz</aliyun.access.secret>
                <aliyun.oss.endpoint>https://oss-ap-southeast-1.aliyuncs.com</aliyun.oss.endpoint>
                <sms.send.host>http://smssh1.253.com/msg/send/json</sms.send.host>
                <sms.send.user>N40267</sms.send.user>
                <sms.send.pass>6p662FiSRF3kub3A</sms.send.pass>
                <sms.send.inthost>http://intapi.253.com/send/json</sms.send.inthost>
                <sms.send.intuser>I25027</sms.send.intuser>
                <sms.send.intpass>+yXK72yjjnJRVYhq</sms.send.intpass>
                <email.provider>custom</email.provider>
                <amazon.ses.host>email-smtp.eu-west-1.amazonaws.com</amazon.ses.host>
                <amazon.ses.port>587</amazon.ses.port>
                <amazon.ses.provider>biex</amazon.ses.provider>
                <amazon.ses.biex.personal>BIEX Notifications</amazon.ses.biex.personal>
                <amazon.ses.biex.username>v4ZlXDIxS/a0HhIGfI/TZEzUUpQINKxS</amazon.ses.biex.username>
                <amazon.ses.biex.password>NEvS80wuPPefi475yUxdSyItLhk7Pez58XgwX6JlSmFrpsU33K8rzU5/jUUnrZGM</amazon.ses.biex.password>
                <amazon.ses.biex.fromuser>service@biex.com</amazon.ses.biex.fromuser>
                <amazon.ses.bitms.personal>BITMS Notifications</amazon.ses.bitms.personal>
                <amazon.ses.bitms.username>82ZE1VpIeeHYiYQtXFeLVIb1wR50pNfl</amazon.ses.bitms.username>
                <amazon.ses.bitms.password>JCZQOMh8fiSBuGabwwcb2KO2+M9UDvX3LI+wFVj8Ta3HCVV773zAWo140A9F4Of7</amazon.ses.bitms.password>
                <amazon.ses.bitms.fromuser>service@bitms.com</amazon.ses.bitms.fromuser>
                <email.host>smtp.163.com</email.host>
                <email.username>a928494847@163.com</email.username>
                <email.password>hcj2019</email.password>
                <database.sql.dialect>mysql</database.sql.dialect>
                <master.jdbc.url>jdbc:mysql://47.97.165.115:3306/exchangev1?failOverReadOnly=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;allowMultiQueries=true&amp;nullCatalogMeansCurrent=true</master.jdbc.url>
                <master.jdbc.poolname>HikariPool1</master.jdbc.poolname>
                <master.jdbc.username>root</master.jdbc.username>
                <master.jdbc.password>B8RQuMP25CKZtsU9Z/xlcQ==</master.jdbc.password>
                <slave1.jdbc.url>${master.jdbc.url}</slave1.jdbc.url>
                <slave1.jdbc.poolname>HikariPool1</slave1.jdbc.poolname>
                <slave1.jdbc.username>root</slave1.jdbc.username>
                <slave1.jdbc.password>B8RQuMP25CKZtsU9Z/xlcQ==</slave1.jdbc.password>
                <zookeeper.address>zookeeper://127.0.0.1:2181</zookeeper.address>
                <kafkaserver.url>127.0.0.1:9092</kafkaserver.url>
                <mongodb.host>127.0.0.1</mongodb.host>
                <mongodb.port>27017</mongodb.port>
                <mongodb.database>appsDev</mongodb.database>
                <redis.conntype>single</redis.conntype><!--cluster-->
                <cluster.nodes>127.0.0.1:6377,127.0.0.1:6378,127.0.0.1:6379</cluster.nodes>
                <redis.host>127.0.0.1</redis.host>
                <redis.timeout>5000</redis.timeout>
                <redis.port>6379</redis.port>
                <redis.password>XpVFvpTuo4T0q8P8JQWnRdTz2EymvnU08WAWvwbw</redis.password>
                <wivpay.payUrl>http://112.14.45.72:9182/gate-pay/unifiedorder/in</wivpay.payUrl>
                <wivpay.payQueryUrl>http://112.14.45.72:9182/gate-pay/queryorder/in</wivpay.payQueryUrl>
                <wivpay.notifyUrl>https://ckjqr.xiaomy.net/api/payment/wivpay/in/notify</wivpay.notifyUrl>
                <wivpay.redirectUrl>http://ckjqr.xiaomy.net/api/payment/wivpay/in/redirect</wivpay.redirectUrl>
                <wivpay.merchantSn>3b11969f45c04e7da519d4834ac6a7df</wivpay.merchantSn>
                <wivpay.merchantAk>d826524632</wivpay.merchantAk>
                <wivpay.merchantSk>92449c375397461098f18db0e6b108dc</wivpay.merchantSk>
                <wivpay.channelAliasName>LuckyboxKingEP</wivpay.channelAliasName>
                <globalpay.rootUrl>https://api.globalpay.land</globalpay.rootUrl>
                <globalpay.mchno>M1718342348</globalpay.mchno>
                <globalpay.appid>1801484496742526978</globalpay.appid>
                <globalpay.payInNotifyUrl>https://ckjqr.xiaomy.net/api/payment/globalpay/in/notify</globalpay.payInNotifyUrl>
                <globalpay.payOutNotifyUrl>https://ckjqr.xiaomy.net/api/payment/globalpay/out/notify</globalpay.payOutNotifyUrl>
                <globalpay.key>kfihra6qsme0n1iavsytxknfqf505iusga5ervs26v45y188b8ad622jau92s80cgtgl3djw1oqqmyqcp36i1vopi1soo2k1i818hmhak4224baar1zcpocgggtsp0d9</globalpay.key>
                <openim.apiRoot>http://121.41.226.80:10002</openim.apiRoot>
                <openim.secret>openIM123</openim.secret>
                <openim.adminAccount>imAdmin</openim.adminAccount>
                <openim.adminPwd>openIM123</openim.adminPwd>
                <openim.authKey>authKey</openim.authKey>
                <openim.livekit.server>ws://121.41.226.80:7880</openim.livekit.server>
                <openim.livekit.appkey>APIftrpEkL9x2pa</openim.livekit.appkey>
                <openim.livekit.appsecret>23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3</openim.livekit.appsecret>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>exchangebiz-test</id>
            <properties>
                <env>exchangebiz-test</env>
                <withdraw.interface.switch>FALSE</withdraw.interface.switch>
                <port.admin>9280</port.admin>
                <port.app>9281</port.app>
                <port.web>9282</port.web>
                <port.api>9283</port.api>
                <port.socket>9284</port.socket>
                <port.rpcServer>12310</port.rpcServer>
                <jpush.appkey>e6b7fda65d7cf7e8b3a</jpush.appkey>
                <jpush.secret>aa46dd030b3d7e891</jpush.secret>
                <weibo.appkey>11111</weibo.appkey>
                <weibo.secret>11111</weibo.secret>
                <weibo.redirect>http://baidu.com</weibo.redirect>
                <qq.appkey>11111</qq.appkey>
                <qq.secret>11111</qq.secret>
                <qq.redirect>http://baidu.com</qq.redirect>
                <!-- 微信小程序 -->
                <weixin.appkey>wxfc4526888e890cdd</weixin.appkey>
                <weixin.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.secret>
                <weixin.open.appkey>wxfc4526888e890cdd</weixin.open.appkey>
                <weixin.open.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.open.secret>
                <weixin.redirect>http://webfhsc.vipgz4.91tunnel.com/api</weixin.redirect>
                <!-- 微信小程序 -->
                <aliyun.afs.appkey>FFFF00000000</aliyun.afs.appkey>
                <aliyun.access.key>LTAI5tBAKUNBfCswtMQgGPZT</aliyun.access.key>
                <aliyun.access.secret>AEcdi4R8hZUHZxxnDSsMia4xclJOFz</aliyun.access.secret>
                <aliyun.oss.endpoint>https://oss-ap-southeast-1.aliyuncs.com</aliyun.oss.endpoint>
                <sms.send.host>http://smssh1.253.com/msg/send/json</sms.send.host>
                <sms.send.user>N40267</sms.send.user>
                <sms.send.pass>6p662FiSRF3kub3A</sms.send.pass>
                <sms.send.inthost>http://intapi.253.com/send/json</sms.send.inthost>
                <sms.send.intuser>I25027</sms.send.intuser>
                <sms.send.intpass>+yXK72yjjnJRVYhq</sms.send.intpass>
                <email.provider>custom</email.provider>
                <amazon.ses.host>email-smtp.eu-west-1.amazonaws.com</amazon.ses.host>
                <amazon.ses.port>587</amazon.ses.port>
                <amazon.ses.provider>biex</amazon.ses.provider>
                <amazon.ses.biex.personal>BIEX Notifications</amazon.ses.biex.personal>
                <amazon.ses.biex.username>v4ZlXDIxS/a0HhIGfI/TZEzUUpQINKxS</amazon.ses.biex.username>
                <amazon.ses.biex.password>NEvS80wuPPefi475yUxdSyItLhk7Pez58XgwX6JlSmFrpsU33K8rzU5/jUUnrZGM</amazon.ses.biex.password>
                <amazon.ses.biex.fromuser>service@biex.com</amazon.ses.biex.fromuser>
                <amazon.ses.bitms.personal>BITMS Notifications</amazon.ses.bitms.personal>
                <amazon.ses.bitms.username>82ZE1VpIeeHYiYQtXFeLVIb1wR50pNfl</amazon.ses.bitms.username>
                <amazon.ses.bitms.password>JCZQOMh8fiSBuGabwwcb2KO2+M9UDvX3LI+wFVj8Ta3HCVV773zAWo140A9F4Of7</amazon.ses.bitms.password>
                <amazon.ses.bitms.fromuser>service@bitms.com</amazon.ses.bitms.fromuser>
                <email.host>smtp.gmail.com</email.host>
                <email.username>wivpalcs@gmail.com</email.username>
                <email.password>rwxrrsftfoquktnv</email.password>
                <database.sql.dialect>mysql</database.sql.dialect>
                <master.jdbc.url>jdbc:mysql://127.0.0.1:3306/exchangev1?failOverReadOnly=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;allowMultiQueries=true&amp;nullCatalogMeansCurrent=true</master.jdbc.url>
                <master.jdbc.poolname>HikariPool1</master.jdbc.poolname>
                <master.jdbc.username>root</master.jdbc.username>
                <master.jdbc.password>B8RQuMP25CKZtsU9Z/xlcQ==</master.jdbc.password>
                <slave1.jdbc.url>${master.jdbc.url}</slave1.jdbc.url>
                <slave1.jdbc.poolname>HikariPool1</slave1.jdbc.poolname>
                <slave1.jdbc.username>root</slave1.jdbc.username>
                <slave1.jdbc.password>B8RQuMP25CKZtsU9Z/xlcQ==</slave1.jdbc.password>
                <zookeeper.address>zookeeper://127.0.0.1:2181</zookeeper.address>
                <kafkaserver.url>127.0.0.1:9092</kafkaserver.url>
                <mongodb.host>127.0.0.1</mongodb.host>
                <mongodb.port>27017</mongodb.port>
                <mongodb.database>appsDev</mongodb.database>
                <redis.conntype>single</redis.conntype><!--cluster-->
                <cluster.nodes>127.0.0.1:6377,127.0.0.1:6378,127.0.0.1:6379</cluster.nodes>
                <redis.host>127.0.0.1</redis.host>
                <redis.timeout>5000</redis.timeout>
                <redis.port>6389</redis.port>
                <redis.password>XpVFvpTuo4T0q8P8JQWnRdTz2EymvnU08WAWvwbw</redis.password>
                <wivpay.payUrl>http://112.14.45.72:9182/gate-pay/unifiedorder/in</wivpay.payUrl>
                <wivpay.payQueryUrl>http://112.14.45.72:9182/gate-pay/queryorder/in</wivpay.payQueryUrl>
                <wivpay.notifyUrl>http://112.14.45.72:9992/api/payment/wivpay/in/notify</wivpay.notifyUrl>
                <wivpay.redirectUrl>http://112.14.45.72:9992/api/payment/wivpay/in/redirect</wivpay.redirectUrl>
                <wivpay.merchantSn>3b11969f45c04e7da519d4834ac6a7df</wivpay.merchantSn>
                <wivpay.merchantAk>d826524632</wivpay.merchantAk>
                <wivpay.merchantSk>92449c375397461098f18db0e6b108dc</wivpay.merchantSk>
                <wivpay.channelAliasName>LuckyboxKingEP</wivpay.channelAliasName>
                <globalpay.rootUrl>https://api.globalpay.land</globalpay.rootUrl>
                <globalpay.mchno>M1718342348</globalpay.mchno>
                <globalpay.appid>1801484496742526978</globalpay.appid>
                <globalpay.payInNotifyUrl>http://112.14.45.72:9992/api/payment/globalpay/in/notify</globalpay.payInNotifyUrl>
                <globalpay.payOutNotifyUrl>http://112.14.45.72:9992/api/payment/globalpay/out/notify</globalpay.payOutNotifyUrl>
                <globalpay.key>kfihra6qsme0n1iavsytxknfqf505iusga5ervs26v45y188b8ad622jau92s80cgtgl3djw1oqqmyqcp36i1vopi1soo2k1i818hmhak4224baar1zcpocgggtsp0d9</globalpay.key>
                <openim.apiRoot>http://121.41.226.80:10002</openim.apiRoot>
                <openim.secret>openIM123</openim.secret>
                <openim.adminAccount>imAdmin</openim.adminAccount>
                <openim.adminPwd>openIM123</openim.adminPwd>
                <openim.authKey>authKey</openim.authKey>
                <openim.livekit.server>ws://121.41.226.80:7880</openim.livekit.server>
                <openim.livekit.appkey>APIftrpEkL9x2pa</openim.livekit.appkey>
                <openim.livekit.appsecret>23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3</openim.livekit.appsecret>
            </properties>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>exchangebiz-prod</id>
            <properties>
                <env>exchangebiz-prod</env>
                <withdraw.interface.switch>TRUE</withdraw.interface.switch>
                <port.admin>9280</port.admin>
                <port.app>9281</port.app>
                <port.web>9282</port.web>
                <port.api>9283</port.api>
                <port.socket>9284</port.socket>
                <port.rpcServer>12310</port.rpcServer>
                <jpush.appkey>e6b7fda65d7cf7e8b3a</jpush.appkey>
                <jpush.secret>aa46dd030b3d7e891</jpush.secret>
                <weibo.appkey>11111</weibo.appkey>
                <weibo.secret>11111</weibo.secret>
                <weibo.redirect>http://baidu.com</weibo.redirect>
                <qq.appkey>11111</qq.appkey>
                <qq.secret>11111</qq.secret>
                <qq.redirect>http://baidu.com</qq.redirect>
                <!-- 微信小程序 -->
                <weixin.appkey>wxfc4526888e890cdd</weixin.appkey>
                <weixin.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.secret>
                <weixin.open.appkey>wxfc4526888e890cdd</weixin.open.appkey>
                <weixin.open.secret>29d570bf7db8e0d20fb3b459f5701e1e</weixin.open.secret>
                <weixin.redirect>http://webfhsc.vipgz4.91tunnel.com/api</weixin.redirect>
                <!-- 微信小程序 -->
                <aliyun.afs.appkey>FFFF00000000</aliyun.afs.appkey>
                <aliyun.access.key>LTAI5tBAKUNBfCswtMQgGPZT</aliyun.access.key>
                <aliyun.access.secret>AEcdi4R8hZUHZxxnDSsMia4xclJOFz</aliyun.access.secret>
                <aliyun.oss.endpoint>https://oss-ap-southeast-1.aliyuncs.com</aliyun.oss.endpoint>
                <sms.send.host>http://smssh1.253.com/msg/send/json</sms.send.host>
                <sms.send.user>N40267</sms.send.user>
                <sms.send.pass>6p662FiSRF3kub3A</sms.send.pass>
                <sms.send.inthost>http://intapi.253.com/send/json</sms.send.inthost>
                <sms.send.intuser>I25027</sms.send.intuser>
                <sms.send.intpass>+yXK72yjjnJRVYhq</sms.send.intpass>
                <email.provider>custom</email.provider>
                <amazon.ses.host>email-smtp.eu-west-1.amazonaws.com</amazon.ses.host>
                <amazon.ses.port>587</amazon.ses.port>
                <amazon.ses.provider>biex</amazon.ses.provider>
                <amazon.ses.biex.personal>BIEX Notifications</amazon.ses.biex.personal>
                <amazon.ses.biex.username>v4ZlXDIxS/a0HhIGfI/TZEzUUpQINKxS</amazon.ses.biex.username>
                <amazon.ses.biex.password>NEvS80wuPPefi475yUxdSyItLhk7Pez58XgwX6JlSmFrpsU33K8rzU5/jUUnrZGM</amazon.ses.biex.password>
                <amazon.ses.biex.fromuser>service@biex.com</amazon.ses.biex.fromuser>
                <amazon.ses.bitms.personal>BITMS Notifications</amazon.ses.bitms.personal>
                <amazon.ses.bitms.username>82ZE1VpIeeHYiYQtXFeLVIb1wR50pNfl</amazon.ses.bitms.username>
                <amazon.ses.bitms.password>JCZQOMh8fiSBuGabwwcb2KO2+M9UDvX3LI+wFVj8Ta3HCVV773zAWo140A9F4Of7</amazon.ses.bitms.password>
                <amazon.ses.bitms.fromuser>service@bitms.com</amazon.ses.bitms.fromuser>
                <email.host>smtp.gmail.com</email.host>
                <email.username>wivpalcs@gmail.com</email.username>
                <email.password>wivpal927a</email.password>
                <database.sql.dialect>mysql</database.sql.dialect>
                <master.jdbc.url>jdbc:mysql://172.31.16.135:3306/exchangebiz?failOverReadOnly=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;allowMultiQueries=true&amp;nullCatalogMeansCurrent=true</master.jdbc.url>
                <master.jdbc.poolname>HikariPool1</master.jdbc.poolname>
                <master.jdbc.username>skyadmin</master.jdbc.username>
                <master.jdbc.password>7DEtMmWm9HDBXo74Xh2ID95lHf2pliIc</master.jdbc.password>
                <slave1.jdbc.url>${master.jdbc.url}</slave1.jdbc.url>
                <slave1.jdbc.poolname>HikariPool1</slave1.jdbc.poolname>
                <slave1.jdbc.username>skyadmin</slave1.jdbc.username>
                <slave1.jdbc.password>7DEtMmWm9HDBXo74Xh2ID95lHf2pliIc</slave1.jdbc.password>
                <zookeeper.address>zookeeper://127.0.0.1:2183</zookeeper.address>
                <kafkaserver.url>127.0.0.1:9092</kafkaserver.url>
                <mongodb.host>127.0.0.1</mongodb.host>
                <mongodb.port>27017</mongodb.port>
                <mongodb.database>appsProd</mongodb.database>
                <redis.conntype>single</redis.conntype><!--cluster-->
                <cluster.nodes>127.0.0.1:6377,127.0.0.1:6378,127.0.0.1:6379</cluster.nodes>
                <redis.host>127.0.0.1</redis.host>
                <redis.timeout>5000</redis.timeout>
                <redis.port>63279</redis.port>
                <redis.password></redis.password>
                <wivpay.payUrl>https://api.wivpay.com/gate-pay/unifiedorder/in</wivpay.payUrl>
                <wivpay.payQueryUrl>https://api.wivpay.com/gate-pay/queryorder/in</wivpay.payQueryUrl>
                <wivpay.notifyUrl>https://app.luckyboxpk.com/api/payment/wivpay/in/notify</wivpay.notifyUrl>
                <wivpay.redirectUrl>https://app.luckyboxpk.com/api/payment/wivpay/in/redirect</wivpay.redirectUrl>
                <wivpay.merchantSn>e8947dddcb4a476f9cbdb0a63433f2b8</wivpay.merchantSn>
                <wivpay.merchantAk>8541849841</wivpay.merchantAk>
                <wivpay.merchantSk>2f1d8af988d64035a80e936121b93732</wivpay.merchantSk>
                <wivpay.channelAliasName>LuckyboxKingEP</wivpay.channelAliasName>
                <globalpay.rootUrl>https://api.globalpay.land</globalpay.rootUrl>
                <globalpay.mchno>M1718342348</globalpay.mchno>
                <globalpay.appid>1801484496742526978</globalpay.appid>
                <globalpay.payInNotifyUrl>https://app.luckyboxpk.com/api/payment/globalpay/in/notify</globalpay.payInNotifyUrl>
                <globalpay.payOutNotifyUrl>https://app.luckyboxpk.com/api/payment/globalpay/out/notify</globalpay.payOutNotifyUrl>
                <globalpay.key>kfihra6qsme0n1iavsytxknfqf505iusga5ervs26v45y188b8ad622jau92s80cgtgl3djw1oqqmyqcp36i1vopi1soo2k1i818hmhak4224baar1zcpocgggtsp0d9</globalpay.key>
                <openim.apiRoot>http://121.41.226.80:10002</openim.apiRoot>
                <openim.secret>openIM123</openim.secret>
                <openim.adminAccount>imAdmin</openim.adminAccount>
                <openim.adminPwd>openIM123</openim.adminPwd>
                <openim.authKey>authKey</openim.authKey>
                <openim.livekit.server>ws://121.41.226.80:7880</openim.livekit.server>
                <openim.livekit.appkey>APIftrpEkL9x2pa</openim.livekit.appkey>
                <openim.livekit.appsecret>23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3</openim.livekit.appsecret>
            </properties>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>nexus</id>
            <name>Nexus</name>
            <url>https://maven.aliyun.com/repository/public</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>com.e-iceblue</id>
            <name>e-iceblue</name>
            <url>https://repo.e-iceblue.cn/repository/maven-public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>nexus</id>
            <name>Nexus</name>
            <url>https://maven.aliyun.com/repository/public</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>

</project>
