#file output config
subpackage=gen
basepackage=com.anyex.apps
java_file_output_directory=C:/Users/xueke/Desktop/apps/java
page_file_output_directory=C:/Users/xueke/Desktop/apps/html
#<<DB CONFIG>>
#jdbc.schema=apps
#jdbc.catalog=apps
#jdbc.username=root
#jdbc.password=root
#jdbc.schema=SYSDBA
#jdbc.catalog=
#jdbc.username=SYSDBA
#jdbc.password=zjeasy@123
jdbc.schema=exchangebiz
jdbc.catalog=exchangebiz
jdbc.username=skyadmin
jdbc.password=2G4@Sky2023&*%FGJhliv2#23
# <<Oracle>>
#jdbc.url=jdbc:oracle:thin:@192.168.31.45:1521:orcl
#jdbc.driver=oracle.jdbc.driver.OracleDriver
# <<MySql>>
jdbc.url=jdbc:mysql://112.14.45.72:3306/exchangebiz
jdbc.driver=com.mysql.cj.jdbc.Driver
# <<DMv8>>
#jdbc.url=jdbc:dm://176.1.1.181:5236?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#jdbc.driver=dm.jdbc.driver.DmDriver
# <<JTDs for sqlserver>>
#jdbc.driver=net.sourceforge.jtds.jdbc.Driver
#jdbc.url="jdbc:jtds:sqlserver://192.168.0.102:1433/[database];tds=8.0;lastupdatecount=true"
# <<PostgreSql>>
#jdbc.driver=org.postgresql.Driver
#jdbc.url=jdbc:postgresql://localhost/[database]
# <<Sybase>>
#jdbc.driver=com.sybase.jdbc.SybDriver
#jdbc.url=jdbc:sybase:Tds:localhost:5007/[database]
# <<DB2>>
#jdbc.driver=com.ibm.db2.jdbc.app.DB2Driver
#jdbc.url=jdbc:db2://localhost:5000/[database]


